# Generated by Django 5.1.7 on 2026-09-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
